# Generated by Django 5.2.14 on 2026-05-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_agreements', '0003_agreement_prepaid_and_line_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementlineitem',
            name='annual_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total for the year if different from qty x price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agreementlineitem',
            name='description',
            field=models.TextField(blank=True, help_text="Details about what's included"),
        ),
        migrations.AlterField(
            model_name='agreementlineitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agreementlineitem',
            name='service_name',
            field=models.CharField(help_text='e.g. Mowing, Mulch, Spring Cleanup', max_length=200),
        ),
        migrations.AlterField(
            model_name='agreementlineitem',
            name='times_expected',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many times this should be done per year', null=True),
        ),
        migrations.AlterField(
            model_name='agreementlineitem',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. visit, yard, application', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='prepaid',
            field=models.BooleanField(default=False, help_text='Client paid upfront for the year. Skip auto-invoicing for services covered by this agreement.'),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='prepaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount already paid. Used for tracking only.', max_digits=10, null=True),
        ),
    ]
