# Generated by Django 5.2.10 on 2026-01-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_service_invoicelineitem_service'),
        ('jobs', '0003_job_route_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='jobs.job'),
        ),
    ]
