# Generated by Django 6.0.2 on 2026-02-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoicelineitem_material_estimatelineitem_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='fertilizing_config',
            field=models.JSONField(blank=True, help_text='Stores fertilizing calculator inputs when item_type=fertilizing', null=True),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='item_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('fertilizing', 'Fertilizing')], default='standard', help_text='Select Fertilizing to show estimator options', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='is_addon',
            field=models.BooleanField(default=False, verbose_name='Optional'),
        ),
    ]
