# Generated by Django 6.0.2 on 2026-02-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_fertilizing_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='mowing_config',
            field=models.JSONField(blank=True, help_text='Stores mowing calculator inputs when item_type=mowing', null=True),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='mulch_config',
            field=models.JSONField(blank=True, help_text='Stores mulch calculator inputs when item_type=mulch', null=True),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='item_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('fertilizing', 'Fertilizing'), ('mulch', 'Mulch'), ('mowing', 'Mowing')], default='standard', help_text='Service type for estimator options', max_length=20),
        ),
    ]
