# Generated by Django 6.0.2 on 2026-02-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoicelineitem_revenue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_token',
            field=models.CharField(blank=True, help_text="Secret token for the customer 'mark as paid' link. Set when invoice is sent.", max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='title',
            field=models.CharField(default='Field Ops Service Estimate', max_length=255),
        ),
    ]
