# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_add_payment_methods_and_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='total_override',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='If set, this amount is used as the line total instead of materials + labor.',
                max_digits=10,
                null=True
            ),
        ),
    ]
