# Generated by Django 6.0.2 on 2026-02-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoice_approval_and_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, help_text='When a payment reminder email was last sent (for automated reminders).', null=True),
        ),
    ]
