# Generated by Django 6.0.2 on 2026-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_payment_reminders_and_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Charge ID (from payment intent)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID for this invoice payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Payment Intent ID (from checkout session)', max_length=255, null=True),
        ),
    ]
