# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_auto_invoice'),
        ('billing', '0017_invoice_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='custom_field_values',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Values for company-defined custom fields (e.g. PO number, license #). Keys match DocumentTemplate custom_fields.',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_field_values',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Values for company-defined custom fields. Keys match DocumentTemplate custom_fields.',
            ),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('estimate', 'Estimate'), ('invoice', 'Invoice')], max_length=20)),
                ('name', models.CharField(help_text='e.g. Professional, Minimal', max_length=100)),
                ('template_key', models.CharField(blank=True, help_text='Built-in template key (professional, minimal, modern) or leave blank for custom.', max_length=50)),
                ('is_default', models.BooleanField(default=True, help_text='Use this template when generating documents of this type.')),
                ('primary_color', models.CharField(default='#22c55e', help_text='Hex color for headers and accents', max_length=7)),
                ('header_text', models.TextField(blank=True, help_text='Optional text or HTML shown at the top of the document (e.g. tagline, license number).')),
                ('footer_text', models.TextField(blank=True, help_text='Optional text or HTML shown at the bottom (e.g. thank you, payment terms).')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions shown on the document.')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='List of custom fields to show on every document. Each: {key, label, type, required}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='businesses.business')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
