# Generated by Django 6.0.3 on 2026-03-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_fertilizerproduct_fertilizerapplication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fertilizerapplication',
            new_name='billing_fer_propert_e49d48_idx',
            old_name='billing_fer_propert_idx',
        ),
        migrations.RenameIndex(
            model_name='fertilizerapplication',
            new_name='billing_fer_busines_42a39c_idx',
            old_name='billing_fer_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='googlemapsapiusage',
            new_name='billing_goo_busines_94aadc_idx',
            old_name='billing_goo_busines_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='googlemapsapiusage',
            new_name='billing_goo_date_e74748_idx',
            old_name='billing_goo_date_idx',
        ),
    ]
