# Generated by Django 6.0.3 on 2026-03-05 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_rename_billing_fer_propert_idx_billing_fer_propert_e49d48_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerapplication',
            name='applied_by',
            field=models.ForeignKey(blank=True, help_text='Technician who applied the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fertilizer_applications_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fertilizerapplication',
            name='weather_conditions',
            field=models.CharField(blank=True, choices=[('clear', 'Clear'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('overcast', 'Overcast'), ('light_rain', 'Light Rain')], help_text='Weather conditions at time of application', max_length=20),
        ),
        migrations.AddField(
            model_name='fertilizerapplication',
            name='weather_temp_f',
            field=models.SmallIntegerField(blank=True, help_text='Temperature (°F) at time of application', null=True),
        ),
        migrations.AddField(
            model_name='fertilizerapplication',
            name='weather_wind_mph',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Wind speed (mph) at time of application', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerproduct',
            name='application_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended lbs per 1,000 sq ft', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerproduct',
            name='epa_registration_number',
            field=models.CharField(blank=True, help_text='EPA registration number for compliance tracking', max_length=50),
        ),
        migrations.AddField(
            model_name='fertilizerproduct',
            name='nitrogen_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nitrogen percentage from product label (e.g., 32.00 for 32-0-4)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerproduct',
            name='phosphorus_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Phosphorus percentage from product label', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerproduct',
            name='potassium_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potassium percentage from product label', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerproduct',
            name='product_type',
            field=models.CharField(choices=[('granular', 'Granular'), ('liquid', 'Liquid')], default='granular', help_text='Affects unit display in calculators', max_length=20),
        ),
    ]
