# Generated by Django 6.0.3 on 2026-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_fertilizerapplication_applied_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='title',
            field=models.CharField(default='Tradevo Service Estimate', max_length=255),
        ),
    ]
