# Generated by Django 6.0.3 on 2026-03-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_estimate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='site_visit_date',
            field=models.DateField(blank=True, help_text='Date of the site visit.', null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='site_visit_notes',
            field=models.TextField(blank=True, help_text='Internal notes from site visit. Not shown on client estimate.'),
        ),
    ]
