# Generated by Django 6.0.3 on 2026-03-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_estimate_site_visit_date_estimate_site_visit_notes'),
        ('customers', '0012_property_lawn_square_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates_at_property', to='customers.property'),
        ),
    ]
