# Generated by Django 6.0.3 on 2026-03-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_add_property_to_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='title',
            field=models.CharField(default='FieldLgx Service Estimate', max_length=255),
        ),
    ]
