# Generated by Django 6.0.2 on 2026-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_rebrand_estimate_title_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed dollar amount or percentage value (e.g. 50 for $50 or 50%).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='deposit_required',
            field=models.BooleanField(default=False, help_text='Require a deposit to accept this estimate.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enable_card_payment',
            field=models.BooleanField(default=True, help_text='Allow credit card payment via Stripe for this invoice. Uncheck to disable card payments.'),
        ),
    ]
