# Generated by Django 6.0.2 on 2026-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_estimate_deposit_amount_estimate_deposit_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerproduct',
            name='category',
            field=models.CharField(choices=[('fertilizer', 'Fertilizer'), ('herbicide', 'Herbicide'), ('pre_emergent', 'Pre-Emergent'), ('insecticide', 'Insecticide'), ('fungicide', 'Fungicide'), ('combo', 'Weed & Feed / Combo'), ('other', 'Other')], default='fertilizer', help_text='What type of product (fertilizer, herbicide, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='fertilizerproduct',
            name='product_type',
            field=models.CharField(choices=[('granular', 'Granular'), ('liquid', 'Liquid')], default='granular', help_text='Physical form — affects unit display in calculators', max_length=20),
        ),
    ]
