# Generated by Django 6.0.2 on 2026-03-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_add_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='job_scheduled',
            field=models.BooleanField(default=False, help_text='Whether a job has been created from this accepted estimate'),
        ),
    ]
