# Generated by Django 6.0.2 on 2026-03-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_add_job_scheduled_to_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='font_style',
            field=models.CharField(choices=[('clean', 'Clean Sans-Serif (Helvetica)'), ('serif', 'Classic Serif (Times)'), ('bold', 'Modern Bold (Helvetica-Bold)')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Custom payment instructions shown on invoices'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='show_photos',
            field=models.BooleanField(default=False, help_text='Include property/job photos'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='show_property_address',
            field=models.BooleanField(default=True, help_text='Show service address on document'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='show_service_date',
            field=models.BooleanField(default=True, help_text='Show service/scheduled date'),
        ),
    ]
