# Generated by Django 6.0.2 on 2026-03-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_promotion'),
        ('customers', '0016_add_contract_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='detail_description',
            field=models.TextField(blank=True, default='', help_text='Optional detailed description shown below the service name on the estimate.'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='detail_description',
            field=models.TextField(blank=True, default='', help_text='Optional detailed description shown below the service name on the invoice.'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='buy_quantity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Buy this many...', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='current_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many the customer has completed so far'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a business-wide promotion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (e.g. 10 for 10%) or fixed dollar amount', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='free_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='...get this many free', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(help_text='e.g. Buy 5 Fertilization Treatments, Get 6th Free', max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='service_name',
            field=models.CharField(blank=True, help_text='Which service this applies to (e.g. Fertilization, Mowing)', max_length=100),
        ),
    ]
