# Generated by Django 6.0.2 on 2026-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_add_detail_description_to_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was marked as paid.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('card', 'Credit/Debit Card'), ('cash', 'Cash'), ('check', 'Check'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('cashapp', 'Cash App'), ('paypal', 'PayPal'), ('ach', 'ACH/Bank Transfer'), ('other', 'Other')], default='', help_text='How the client paid this invoice.', max_length=20),
        ),
    ]
