# Generated by Django 5.2.14 on 2026-05-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_estimate_accepted_optional_item_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='title',
            field=models.CharField(default='FIELDLGX Service Estimate', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('approved_sent', 'Approved & sent'), ('sent', 'Sent'), ('paid', 'Marked paid'), ('auto_charged', 'Auto-charged'), ('auto_charge_failed', 'Auto-charge failed'), ('void', 'Voided'), ('line_items_edited', 'Line items edited'), ('dates_updated', 'Dates updated')], max_length=32),
        ),
    ]
