# Generated by Django 5.2.10 on 2026-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_recurringjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='route_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
