# Generated by Django 5.2.10 on 2026-01-09 12:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_route_order'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(default='visit', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='jobs.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.servicetemplate')),
            ],
        ),
    ]
