# Generated by Django 5.2.10 on 2026-01-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_period_end_invoice_period_start_and_more'),
        ('jobs', '0004_jobserviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobserviceitem',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobserviceitem',
            name='billed_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_job_items', to='billing.invoice'),
        ),
    ]
