# Generated by Django 6.0.2 on 2026-02-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_crews_colors_coords'),
        ('jobs', '0005_jobserviceitem_billed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assign to individual employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for calendar/route display', max_length=7)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='businesses.business')),
                ('crew_leader', models.ForeignKey(blank=True, limit_choices_to={'role': 'crew'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_crews', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'crew'}, related_name='crew_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_crew',
            field=models.ForeignKey(blank=True, help_text='Or assign to a crew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.crew'),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='assigned_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_jobs', to='jobs.crew'),
        ),
    ]
