# Generated by Django 6.0.2 on 2026-02-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_crews_colors_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Optional start time for week/day view', null=True),
        ),
    ]
