# Generated by Django 6.0.2 on 2026-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Null = unscheduled (accepted but not yet on calendar)', null=True),
        ),
    ]
