# Generated by Django 6.0.2 on 2026-02-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_labor_material_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recurring_job',
            field=models.ForeignKey(blank=True, help_text='Set when this job was auto-generated from a recurring schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_jobs', to='jobs.recurringjob'),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='custom_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='When frequency is Custom: repeat every this many days.', null=True),
        ),
        migrations.AddField(
            model_name='recurringjob',
            name='service_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Services to add when generating jobs from this recurrence.'),
        ),
        migrations.AlterField(
            model_name='recurringjob',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom (every N days)')], max_length=20),
        ),
    ]
