# Generated by Django 6.0.2 on 2026-02-19 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_payment_reminders_and_outstanding'),
        ('customers', '0009_recurring_and_fertilization'),
        ('jobs', '0013_job_assignment_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(help_text='When the meeting is scheduled.')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, default=60, help_text='Duration in minutes for calendar display.')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text="When a reminder notification was sent (so we don't send twice).", null=True)),
                ('reminder_hours_before', models.PositiveSmallIntegerField(blank=True, default=24, help_text='Send reminder this many hours before scheduled_at.')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text="Optional: client you're meeting with.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='customers.customer')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
