# Generated by Django 6.0.2 on 2026-02-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_meeting_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this job was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this job as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
