# Generated by Django 6.0.2 on 2026-02-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_completed_by_and_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this job was soft-deleted. Null means not deleted.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
