# Generated by Django 6.0.3 on 2026-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_add_job_note_and_property_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, help_text='Estimated arrival time (for owner use only)', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='technician_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Current technician location (for owner tracking only)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='technician_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Current technician location (for owner tracking only)', max_digits=10, null=True),
        ),
    ]
