# Generated by Django 6.0.3 on 2026-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_job_estimated_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='en_route_at',
            field=models.DateTimeField(blank=True, help_text="When crew tapped 'On My Way' and customer was notified.", null=True),
        ),
    ]
