# Generated by Django 6.0.3 on 2026-03-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_jobphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='color',
            field=models.CharField(default='#10b981', help_text='Hex color for calendar/route display', max_length=7),
        ),
        migrations.AlterField(
            model_name='job',
            name='color',
            field=models.CharField(blank=True, help_text='Override color for calendar (hex e.g. #10b981). Leave empty to use crew/employee default.', max_length=7, null=True),
        ),
    ]
