# Generated by Django 6.0.3 on 2026-03-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_rebrand_color_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='color',
            field=models.CharField(default='#22c55e', help_text='Hex color for calendar/route display', max_length=7),
        ),
        migrations.AlterField(
            model_name='job',
            name='color',
            field=models.CharField(blank=True, help_text='Override color for calendar (hex e.g. #22c55e). Leave empty to use crew/employee default.', max_length=7, null=True),
        ),
    ]
