# Generated by Django 6.0.2 on 2026-03-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_add_assigned_employees_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When crew started working on this job (set by start_job action)', null=True),
        ),
    ]
