# Generated by Django 6.0.2 on 2026-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_job_schedule_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skip_reason',
            field=models.CharField(blank=True, default='', help_text='Reason the job was skipped.', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_by_date',
            field=models.DateField(blank=True, help_text='Target date to schedule this job by — shows as a reminder', null=True),
        ),
        migrations.AlterField(
            model_name='recurringjob',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('10day', 'Every 10 Days'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom (every N days)')], max_length=20),
        ),
    ]
