# Generated by Django 6.0.2 on 2026-04-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_add_skip_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day jobs — null means single-day', null=True),
        ),
    ]
