# Generated by Django 6.0.2 on 2026-04-19 00:01

from django.db import migrations, models


def backfill_crews_from_assigned_crew(apps, schema_editor):
    """
    For every existing Job with assigned_crew set, also add that crew to the
    new crews M2M. This maintains the invariant "the primary crew is always
    in the crews list" so queries like `Job.objects.filter(crews__id=X)`
    return the same set of jobs that previously only matched via
    `assigned_crew_id=X`.
    """
    Job = apps.get_model('jobs', 'Job')
    # Iterate only jobs with a primary crew assigned — nothing to backfill otherwise
    # .iterator() keeps memory low even with large tables
    for job in Job.objects.filter(assigned_crew__isnull=False).only('id', 'assigned_crew_id').iterator(chunk_size=500):
        job.crews.add(job.assigned_crew_id)


def clear_backfilled_crews(apps, schema_editor):
    """
    Reverse: clear all crews M2M entries. The field itself is dropped by the
    automatic reverse of AddField, so this just ensures the join table is
    empty before the schema drop (defensive — Django handles the drop
    regardless).
    """
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all().only('id').iterator(chunk_size=500):
        job.crews.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_add_scheduled_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='crews',
            field=models.ManyToManyField(blank=True, help_text='All crews assigned to this job. assigned_crew remains the primary for backward compat.', related_name='multi_assigned_jobs', to='jobs.crew'),
        ),
        migrations.RunPython(
            backfill_crews_from_assigned_crew,
            reverse_code=clear_backfilled_crews,
            hints={'target_db': 'default'},
        ),
    ]
