# Generated by Django 6.0.2 on 2026-04-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_add_job_crews_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobserviceitem',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='For multi-day jobs: which day this line item runs. Null = spans entire job.', null=True),
        ),
    ]
