# Generated by Django 6.0.3 on 2026-03-05 23:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0021_rename_billing_fer_propert_idx_billing_fer_propert_e49d48_idx_and_more'),
        ('businesses', '0026_business_complimentary_access_enabled_and_more'),
        ('customers', '0011_customer_portal_access'),
        ('jobs', '0018_alter_job_estimated_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grass_type', models.CharField(choices=[('cool_season', 'Cool Season'), ('warm_season', 'Warm Season'), ('both', 'Both')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_programs', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomerProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='enrolled', max_length=20)),
                ('pricing_method', models.CharField(choices=[('per_application', 'Per Application'), ('annual_flat', 'Annual Flat'), ('per_sqft', 'Per Sq Ft')], default='per_application', max_length=20)),
                ('price_per_application', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('markup_pct', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='businesses.business')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='customers.property')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='fertilization.fertilizationprogram')),
            ],
            options={
                'ordering': ['-year', 'property__address'],
                'unique_together': {('property', 'program', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProgramRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('target_month_start', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_month_end', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('default_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('crew_instructions', models.TextField(blank=True)),
                ('products', models.ManyToManyField(blank=True, to='billing.fertilizerproduct')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='fertilization.fertilizationprogram')),
            ],
            options={
                'ordering': ['program', 'round_number'],
                'unique_together': {('program', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_round', to='billing.fertilizerapplication')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_rounds', to='fertilization.customerprogramenrollment')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fertilization_rounds', to='jobs.job')),
                ('round_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instances', to='fertilization.programround')),
            ],
            options={
                'ordering': ['enrollment', 'round_number'],
            },
        ),
    ]
