# Generated by Django 6.0.2 on 2026-02-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_crews_colors_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='User-provided total property area for scale calibration', max_digits=12, null=True)),
                ('grass_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pavement_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Sidewalks, parking, driveways (snow removal)', max_digits=12, null=True)),
                ('mulch_bed_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('bush_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_estimates', to='customers.property')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyEstimateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_estimates/%Y/%m/')),
                ('enhanced_image', models.ImageField(blank=True, null=True, upload_to='property_estimates/%Y/%m/')),
                ('segmentation_overlay', models.ImageField(blank=True, null=True, upload_to='property_estimates/%Y/%m/')),
                ('pixel_scale', models.DecimalField(blank=True, decimal_places=6, help_text='Sq ft per pixel (from total_area_sqft / total_pixels)', max_digits=12, null=True)),
                ('raw_grass_pixels', models.BigIntegerField(blank=True, null=True)),
                ('raw_pavement_pixels', models.BigIntegerField(blank=True, null=True)),
                ('raw_mulch_pixels', models.BigIntegerField(blank=True, null=True)),
                ('raw_tree_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_bush_count', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property_estimator.propertyestimate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
