# Generated by Django 5.2.10 on 2026-01-09 12:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_auto_invoice'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('default_unit', models.CharField(choices=[('visit', 'Per visit'), ('yard', 'Per yard'), ('hour', 'Per hour'), ('item', 'Per item')], default='visit', max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_templates', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_unit', models.CharField(blank=True, max_length=20)),
                ('override_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='customers.property')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_rates', to='pricing.servicetemplate')),
            ],
            options={
                'unique_together': {('property', 'service')},
            },
        ),
    ]
