# Generated by Django 6.0.2 on 2026-02-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_propertyservicerate_override_unit'),
        ('pricing', '0002_servicetemplate_revenue_category'),
    ]

    operations = [
    ]
