# Generated by Django 6.0.2 on 2026-03-25 02:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_merge_20260215_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetemplate',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge regardless of calculation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='pricing_method',
            field=models.CharField(choices=[('flat', 'Flat rate'), ('per_sqft', 'Per square foot'), ('per_yard', 'Per yard'), ('per_hour', 'Per hour')], default='flat', help_text='How this service is priced', max_length=20),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='pricing_notes',
            field=models.TextField(blank=True, help_text='Internal notes about pricing for this service'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='rate_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price per square foot (for sqft-based pricing like mowing)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price (flat rate per visit, per yard, per hour, etc.)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='default_unit',
            field=models.CharField(choices=[('visit', 'Per visit'), ('yard', 'Per yard'), ('hour', 'Per hour'), ('item', 'Per item'), ('sqft', 'Per sq ft')], default='visit', max_length=20),
        ),
    ]
