# Generated by Django 6.0.2 on 2026-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Stripe event ID (evt_...)', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Event type (e.g., checkout.session.completed)', max_length=100)),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been successfully processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the event was processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('raw_data', models.JSONField(blank=True, help_text='Full event data (for debugging)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='subscriptio_event_i_187fc2_idx'), models.Index(fields=['event_type', 'processed'], name='subscriptio_event_t_b2a2da_idx')],
            },
        ),
    ]
