# Generated by Django 6.0.4 on 2026-04-28 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0040_business_client_saved_cards_enabled'),
        ('mobile_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('server_id', models.CharField(blank=True, max_length=80)),
                ('local_id', models.CharField(blank=True, max_length=80)),
                ('base_revision', models.CharField(blank=True, max_length=120)),
                ('server_revision', models.CharField(blank=True, max_length=120)),
                ('local_payload', models.JSONField(blank=True, default=dict)),
                ('server_payload', models.JSONField(blank=True, default=dict)),
                ('mergeable_fields', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sync_conflicts', to='businesses.business')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_sync_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
