# Generated by Django 6.0.3 on 2026-03-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0028_business_business_subtype_business_business_type_and_more'),
        ('customers', '0012_property_lawn_square_feet'),
        ('jobs', '0018_alter_job_estimated_arrival_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('furnace', 'Furnace'), ('ac_unit', 'Air Conditioner'), ('heat_pump', 'Heat Pump'), ('boiler', 'Boiler'), ('water_heater', 'Water Heater'), ('thermostat', 'Thermostat'), ('ductwork', 'Ductwork'), ('mini_split', 'Mini Split'), ('panel', 'Electrical Panel'), ('generator', 'Generator'), ('sump_pump', 'Sump Pump'), ('water_softener', 'Water Softener'), ('other', 'Other')], default='other', max_length=30)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('location_in_property', models.CharField(blank=True, help_text='e.g. Basement, Attic, Garage', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='customers.customer')),
                ('service_property', models.ForeignKey(blank=True, db_column='property_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='customers.property')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['customer', 'equipment_type', 'make'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('installation', 'Installation'), ('inspection', 'Inspection'), ('replacement', 'Replacement')], default='maintenance', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('parts_used', models.JSONField(blank=True, default=list, help_text='List of parts/materials used.')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='equipment.equipment')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_service_logs', to='jobs.job')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
