# Generated by Django 5.2.10 on 2026-01-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_invoice',
            field=models.CharField(choices=[('auto', 'Automatically create invoices'), ('manual', 'Manually create invoices')], default='manual', max_length=10),
        ),
    ]
