# Generated by Django 6.0.2 on 2026-02-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_email_smtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Email address estimates are sent from (use same as Gmail above)', max_length=254),
        ),
    ]
