# Generated by Django 6.0.2 on 2026-02-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_estimate_follow_up_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cashapp_cashtag',
            field=models.CharField(blank=True, help_text='Cash App $cashtag (e.g. $YourBusiness). Shown on invoices.', max_length=32),
        ),
        migrations.AddField(
            model_name='business',
            name='venmo_username',
            field=models.CharField(blank=True, help_text='Your Venmo username (e.g. @YourBusiness). Shown on invoices.', max_length=64),
        ),
        migrations.AddField(
            model_name='business',
            name='zelle_email_or_phone',
            field=models.CharField(blank=True, help_text='Email or phone number for Zelle. Shown on invoices.', max_length=128),
        ),
    ]
