# Generated by Django 6.0.2 on 2026-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_add_payment_methods_and_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_invoice_due_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Default number of days from issue date until invoice is due (e.g. 30 for Net 30). Leave blank for no default.', null=True),
        ),
    ]
