# Generated by Django 6.0.2 on 2026-02-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_invoice_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='growing_season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='Last month of growing season (1–12). Default 10 = October.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='growing_season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='First month of growing season for fertilization scheduling (1=Jan … 12=Dec). Default 3 = March.', null=True),
        ),
    ]
