# Generated by Django 6.0.2 on 2026-02-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_recurring_and_fertilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='next_pay_date',
            field=models.DateField(blank=True, help_text='Next date you will run payroll. Used with pay frequency to compute payroll balance.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='pay_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('semimonthly', 'Twice a month (e.g. 1st & 15th)'), ('monthly', 'Monthly')], help_text='How often you run payroll. Set in Financials to show payroll balance on the dashboard.', max_length=20),
        ),
    ]
