# Generated by Django 6.0.2 on 2026-02-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_payroll_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pay_period_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='When pay frequency is Custom: number of days in each pay period (e.g. 10 for every 10 days).', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='pay_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('semimonthly', 'Twice a month (e.g. 1st & 15th)'), ('monthly', 'Monthly'), ('custom', 'Custom (number of days)')], help_text='How often you run payroll. Set in Financials to show payroll balance on the dashboard.', max_length=20),
        ),
    ]
