# Generated by Django 6.0.2 on 2026-02-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_pay_period_days_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pay_specific_days',
            field=models.JSONField(blank=True, help_text='When pay frequency is Specific dates: list of day-of-month numbers, e.g. [1, 15] for 1st and 15th.', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='pay_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('semimonthly', 'Twice a month (e.g. 1st & 15th)'), ('monthly', 'Monthly'), ('custom', 'Custom (number of days)'), ('custom_dates', 'Specific dates (e.g. 1st & 15th)')], help_text='How often you run payroll. Set in Financials to show payroll balance on the dashboard.', max_length=20),
        ),
    ]
