# Generated by Django 6.0.2 on 2026-02-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_pay_specific_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='require_completion_photo',
            field=models.BooleanField(default=False, help_text='If set, crew must upload at least one completion photo before marking the job complete.'),
        ),
    ]
