# Generated by Django 6.0.2 on 2026-02-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_require_completion_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='invoice_reminder_days',
            field=models.CharField(blank=True, default='7,14,21', help_text='Comma-separated days after due date to send reminders (e.g. 7,14,21).', max_length=64),
        ),
        migrations.AddField(
            model_name='business',
            name='invoice_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Send automatic payment reminder emails for overdue invoices.'),
        ),
    ]
