# Generated by Django 5.2.11 on 2026-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_email_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_invoice_send_behavior',
            field=models.CharField(choices=[('draft', 'Create draft invoice (owner reviews before send)'), ('send', 'Automatically approve & send immediately')], default='draft', help_text='For automated per-service invoices: draft-only (recommended) or auto-send.', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='default_invoice_automation_mode',
            field=models.CharField(blank=True, choices=[('', 'Ask each time (owner chooses per completed job)'), ('per_service', 'Per service (create invoice when each job is completed)'), ('monthly', 'Monthly batching (group completed jobs into monthly invoice)')], default='', help_text='Default behavior when a customer does not have invoice frequency set.', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='default_monthly_invoice_send_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Default day (1-28) to send monthly invoices when customer-level day is not set.', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='invoice_email_closing',
            field=models.TextField(blank=True, help_text='Closing line before your contact info (e.g. “Thank you for your business.”). Leave blank for default.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='invoice_email_intro',
            field=models.TextField(blank=True, help_text='Opening line in the invoice email (e.g. “Hi {{customer_name}}, please find your invoice below.”). Leave blank for default.'),
        ),
    ]
