# Generated by Django 6.0.2 on 2026-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_email_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='invoice_email_closing',
            field=models.TextField(blank=True, help_text='Closing line before your contact info (e.g. “Thank you for your business.”). Leave blank for default.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='invoice_email_intro',
            field=models.TextField(blank=True, help_text='Opening line in the invoice email (e.g. “Hi {{customer_name}}, please find your invoice below.”). Leave blank for default.'),
        ),
    ]
