# Generated by Django 5.2.11 on 2026-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_business_auto_invoice_send_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_review_followup_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days between follow-up review requests when client has not responded.'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_review_link',
            field=models.URLField(blank=True, help_text='Your direct Google review link (Place review URL).'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_review_max_attempts',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maximum total review emails per client.'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_review_request_delay_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Hours after payment before first review request is sent.'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_review_requests_enabled',
            field=models.BooleanField(default=False, help_text='Automatically email clients a Google review request after payment.'),
        ),
    ]
