# Generated by Django 5.2.11 on 2026-03-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_business_google_review_followup_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_review_sms_enabled',
            field=models.BooleanField(default=False, help_text='Also send review requests via SMS when client phone is available.'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_review_sms_template',
            field=models.TextField(blank=True, help_text='Optional SMS template. Use {{customer_name}}, {{business_name}}, {{review_link}}.'),
        ),
    ]
