# Generated by Django 5.2.11 on 2026-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_business_google_review_sms_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether initial onboarding flow has been completed for this business.'),
        ),
        migrations.AddField(
            model_name='business',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When onboarding was marked complete.', null=True),
        ),
    ]
