# Generated by Django 5.2.11 on 2026-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0022_business_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='invoice_reminder_require_owner_approval',
            field=models.BooleanField(default=True, help_text='If enabled, automatic reminder jobs require owner-triggered run (safer mode).'),
        ),
    ]
