# Generated by Django 5.2.11 on 2026-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_business_invoice_reminder_require_owner_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='estimate_follow_up_cadence_days',
            field=models.CharField(blank=True, default='3,7,14', help_text='Follow-up cadence days after estimate sent (comma-separated).', max_length=64),
        ),
        migrations.AddField(
            model_name='business',
            name='quote_upsell_suggestions',
            field=models.TextField(blank=True, default='Seasonal fertilizer program\nMulch refresh\nIrrigation tune-up', help_text='Optional upsells to include in follow-up nudges (one per line).'),
        ),
    ]
