# Generated by Django 5.2.11 on 2026-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_business_estimate_follow_up_cadence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan_crew_soft_cap_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional per-business soft cap override for crew users before growth recommendation.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_plan_tier',
            field=models.CharField(choices=[('core', 'Core'), ('growth', 'Growth')], default='core', help_text='Current plan tier for predictable packaging controls.', max_length=20),
        ),
    ]
