# Generated by Django 5.2.11 on 2026-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_business_plan_crew_soft_cap_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='complimentary_access_enabled',
            field=models.BooleanField(default=False, help_text='If enabled by platform admin, this business can access the app without an active paid subscription.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='subscription_plan_tier',
            field=models.CharField(choices=[('solo', 'Solo Starter'), ('core', 'Pro All-Access')], default='core', help_text='Current plan tier for packaging and billing display.', max_length=20),
        ),
    ]
