# Generated by Django 6.0.3 on 2026-03-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0026_business_complimentary_access_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'Eastern'), ('America/Chicago', 'Central'), ('America/Denver', 'Mountain'), ('America/Los_Angeles', 'Pacific'), ('America/Anchorage', 'Alaska'), ('Pacific/Honolulu', 'Hawaii')], default='America/New_York', help_text='All times in the app display in this timezone.', max_length=50),
        ),
    ]
