# Generated by Django 6.0.3 on 2026-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0027_business_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_subtype',
            field=models.CharField(blank=True, choices=[('lawn_care', 'Lawn Care Only'), ('full_service', 'Full-Service Landscaping'), ('residential_hvac', 'Residential HVAC'), ('commercial_hvac', 'Commercial HVAC'), ('both_hvac', 'Residential & Commercial HVAC'), ('residential_plumbing', 'Residential Plumbing'), ('commercial_plumbing', 'Commercial Plumbing'), ('both_plumbing', 'Residential & Commercial Plumbing'), ('residential_electrical', 'Residential Electrical'), ('commercial_electrical', 'Commercial Electrical'), ('both_electrical', 'Residential & Commercial Electrical'), ('residential_cleaning', 'Residential Cleaning'), ('commercial_cleaning', 'Commercial Cleaning'), ('both_cleaning', 'Residential & Commercial Cleaning'), ('general', 'General')], default='full_service', max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('landscaping', 'Landscaping & Lawn Care'), ('hvac', 'HVAC'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('general', 'Other Home Service')], default='landscaping', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='Auto-populated based on business_type.'),
        ),
        migrations.AddField(
            model_name='business',
            name='terminology_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Custom label overrides for terminology engine.'),
        ),
    ]
