# Generated by Django 6.0.3 on 2026-03-07 15:41

import businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0028_business_business_subtype_business_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='booking_enabled',
            field=models.BooleanField(default=False, help_text='Enable the public booking page for this business.'),
        ),
        migrations.AddField(
            model_name='business',
            name='booking_token',
            field=models.CharField(default=businesses.models._default_booking_token, help_text='URL token for public booking page: /book/<token>/', max_length=12, unique=True),
        ),
    ]
