# Generated by Django 6.0.3 on 2026-03-07 15:41

import uuid

import businesses.models
from django.db import migrations, models


def backfill_booking_tokens(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    for business in Business.objects.all():
        business.booking_token = uuid.uuid4().hex[:12]
        business.save(update_fields=["booking_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0028_business_business_subtype_business_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='booking_enabled',
            field=models.BooleanField(default=False, help_text='Enable the public booking page for this business.'),
        ),
        # Step 1: Add booking_token as nullable without unique constraint
        migrations.AddField(
            model_name='business',
            name='booking_token',
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        # Step 2: Backfill unique tokens for all existing rows
        migrations.RunPython(backfill_booking_tokens, migrations.RunPython.noop),
        # Step 3: Apply the unique constraint and default, remove nullable
        migrations.AlterField(
            model_name='business',
            name='booking_token',
            field=models.CharField(default=businesses.models._default_booking_token, help_text='URL token for public booking page: /book/<token>/', max_length=12, unique=True),
        ),
    ]
