# Generated by Django 6.0.3 on 2026-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0029_business_booking_enabled_business_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='quote_upsell_suggestions',
            field=models.TextField(blank=True, default='', help_text='Optional upsells to include in follow-up nudges (one per line).'),
        ),
    ]
