# Generated by Django 6.0.3 on 2026-03-07 19:29

from django.db import migrations


MODULE_DEFAULTS = {
    "landscaping": ["fertilization", "property_estimator", "growing_season", "checklists"],
    "hvac": ["pricebook", "equipment", "service_agreements", "inspections", "checklists"],
    "plumbing": ["pricebook", "equipment", "service_agreements", "inspections", "checklists"],
    "electrical": ["pricebook", "equipment", "service_agreements", "inspections", "checklists"],
    "cleaning": ["checklists", "service_agreements"],
    "general": ["checklists"],
}


def backfill_modules(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    for biz in Business.objects.all():
        if not biz.enabled_modules:
            biz.enabled_modules = list(MODULE_DEFAULTS.get(biz.business_type, []))
            biz.save(update_fields=["enabled_modules"])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0030_alter_business_quote_upsell_suggestions'),
    ]

    operations = [
        migrations.RunPython(backfill_modules, migrations.RunPython.noop),
    ]
