# Generated by Django 6.0.3 on 2026-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0031_backfill_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='notify_crew_en_route',
            field=models.BooleanField(default=True, help_text="Notify client when crew taps 'On My Way'."),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_include_completion_photos',
            field=models.BooleanField(default=True, help_text='Include completion photos in job-completed notifications.'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_job_completed',
            field=models.BooleanField(default=True, help_text='Notify client when a job is marked complete.'),
        ),
        migrations.AddField(
            model_name='business',
            name='notify_job_scheduled',
            field=models.BooleanField(default=True, help_text='Notify client when a job is scheduled or rescheduled.'),
        ),
        migrations.AddField(
            model_name='business',
            name='template_crew_en_route',
            field=models.TextField(blank=True, default='Hi {{customer_name}}, our crew is heading to your property now for {{service_list}}. See you soon!', help_text='SMS/email template for crew-en-route notification.'),
        ),
        migrations.AddField(
            model_name='business',
            name='template_job_completed',
            field=models.TextField(blank=True, default='Hi {{customer_name}}, your {{service_list}} is complete! Thank you for choosing {{business_name}}.', help_text='SMS/email template for job-completed notification.'),
        ),
        migrations.AddField(
            model_name='business',
            name='template_job_scheduled',
            field=models.TextField(blank=True, default="Hi {{customer_name}}, your {{service_list}} with {{business_name}} is scheduled for {{scheduled_date}}. We'll notify you when our crew is on the way!", help_text='SMS/email template for job-scheduled notification.'),
        ),
        migrations.AddField(
            model_name='business',
            name='twilio_account_sid',
            field=models.CharField(blank=True, help_text='Twilio Account SID (starts with AC…)', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='twilio_auth_token',
            field=models.CharField(blank=True, help_text='Twilio Auth Token (stored encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='twilio_from_number',
            field=models.CharField(blank=True, help_text='Twilio phone number for outbound SMS (e.g. +15551234567)', max_length=20),
        ),
    ]
