# Generated by Django 6.0.3 on 2026-03-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0032_business_notify_crew_en_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_subtype',
            field=models.CharField(blank=True, choices=[('lawn_care', 'Lawn Care Only'), ('full_service', 'Full-Service Landscaping')], default='full_service', max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('landscaping', 'Landscaping & Lawn Care')], default='landscaping', max_length=20),
        ),
    ]
