# Generated by Django 6.0.2 on 2026-03-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_alter_business_invoice_email_closing_and_more'),
        ('businesses', '0033_rebrand_color_defaults'),
    ]

    operations = [
    ]
