# Generated by Django 6.0.2 on 2026-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0034_merge_20260320_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='paypal_link',
            field=models.CharField(blank=True, help_text='PayPal.me link or PayPal email (e.g. paypal.me/YourBusiness). Shown on invoices.', max_length=255),
        ),
    ]
