# Generated by Django 6.0.2 on 2026-03-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0035_business_paypal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_fert_price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default price per sq ft per application for fertilization (e.g. 0.0065 = $6.50 per 1000 sq ft).', max_digits=6, null=True),
        ),
    ]
