# Generated by Django 6.0.2 on 2026-03-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0037_business_default_estimate_valid_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='shop_address',
            field=models.CharField(blank=True, help_text='Shop/office address used as start and end point for route optimization', max_length=300),
        ),
        migrations.AlterField(
            model_name='business',
            name='default_estimate_valid_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Default number of days an estimate is valid for. Shown on estimate form, owner can override per estimate.'),
        ),
    ]
