# Generated by Django 6.0.2 on 2026-02-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_and_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color for calendar/route (e.g. #3b82f6). Owner can customize.', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('crew', 'Crew')], default='crew', max_length=10),
        ),
    ]
