# Generated by Django 6.0.2 on 2026-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Platform admin access: can view platform analytics, manage businesses, and access admin features.'),
        ),
    ]
