# Generated by Django 5.2.11 on 2026-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_set_initial_platform_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('platform_enter', 'Platform admin entered business'), ('platform_exit', 'Platform admin exited business'), ('admin_grant', 'Granted platform admin access'), ('admin_revoke', 'Revoked platform admin access'), ('login', 'User login'), ('login_failed', 'Failed login attempt')], max_length=32),
        ),
    ]
