# Generated by Django 6.0.3 on 2026-03-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_employeepayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color for calendar/route (e.g. #10b981). Owner can customize.', max_length=7),
        ),
    ]
