# Generated by Django 6.0.3 on 2026-03-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rebrand_color_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color for calendar/route (e.g. #22c55e). Owner can customize.', max_length=7),
        ),
    ]
