# Generated by Django 6.0.2 on 2026-02-19 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_approved(apps, schema_editor):
    """Existing entries count as approved so timesheets are unchanged."""
    TimeEntry = apps.get_model("time_tracking", "TimeEntry")
    TimeEntry.objects.all().update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_time_off_and_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', help_text='Only approved entries count for payroll.', max_length=20),
        ),
        migrations.RunPython(backfill_approved, migrations.RunPython.noop),
    ]
