# Generated by Codex on 2026-04-28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracking", "0005_timeentry_clock_in_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntryLocationPing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("accuracy_meters", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_entry",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="location_pings", to="time_tracking.timeentry"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_location_pings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-recorded_at"], name="time_tracki_user_id_07e0ec_idx"),
                    models.Index(fields=["time_entry", "-recorded_at"], name="time_tracki_time_en_9b7337_idx"),
                ],
            },
        ),
    ]
