from django.urls import path
from . import views

urlpatterns = [
    path("", views.invoice_list, name="invoice_list"),
    path("outstanding/", views.outstanding_invoices, name="outstanding_invoices"),
    path("monthly/", views.monthly_invoice_list, name="monthly_invoice_list"),
    path("<int:invoice_id>/", views.invoice_detail, name="invoice_detail"),
    path("<int:invoice_id>/update-dates/", views.invoice_update_dates, name="invoice_update_dates"),
    path("<int:invoice_id>/edit-line-items/", views.invoice_edit_line_items, name="invoice_edit_line_items"),
    path("<int:invoice_id>/send/", views.send_invoice, name="send_invoice"),
    path("<int:invoice_id>/resend/", views.resend_invoice, name="resend_invoice"),
    path("<int:invoice_id>/pdf/", views.invoice_pdf, name="invoice_pdf"),
    path("<int:invoice_id>/pay/<str:token>/", views.invoice_pay_page, name="invoice_pay_page"),
    path("<int:invoice_id>/pay/<str:token>/stripe/", views.create_invoice_checkout_session, name="create_invoice_checkout"),
    path("<int:invoice_id>/charge-saved/", views.charge_saved_payment_method, name="charge_saved_payment_method"),
    path("connect/onboarding/", views.connect_onboarding, name="connect_onboarding"),
    path("connect/return/", views.connect_return, name="connect_return"),
    path("connect/dashboard/", views.connect_dashboard, name="connect_dashboard"),
    path("<int:invoice_id>/mark-paid/", views.mark_invoice_paid, name="mark_invoice_paid"),
    path("estimates/", views.estimate_list, name="estimate_list"),
    path("estimates/create/", views.estimate_create, name="estimate_create"),
    path("estimates/create-from-fertilizer/", views.estimate_create_from_fertilizer, name="estimate_create_from_fertilizer"),
    path("estimates/create-from-mulch/", views.estimate_create_from_mulch, name="estimate_create_from_mulch"),
    path("estimates/<int:estimate_id>/", views.estimate_detail, name="estimate_detail"),
    path("estimates/<int:estimate_id>/edit/", views.estimate_edit, name="estimate_edit"),
    path("estimates/<int:estimate_id>/pdf/", views.estimate_pdf, name="estimate_pdf"),
    path("estimates/<int:estimate_id>/send/", views.estimate_send, name="estimate_send"),
    path("estimates/<int:estimate_id>/send-followup/", views.estimate_send_followup, name="estimate_send_followup"),
    path("estimates/<int:estimate_id>/images/add/", views.estimate_add_image, name="estimate_add_image"),
    path("estimates/<int:estimate_id>/view/<str:token>/", views.estimate_client_view, name="estimate_client_view"),
    path("estimates/<int:estimate_id>/accept/<str:token>/", views.estimate_client_accept, name="estimate_client_accept"),
]
