# Generated by Django 5.2.10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0002_business_auto_invoice"),
        ("jobs", "0009_job_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="receipts/")),
                ("receipt_date", models.DateField(help_text="Date on the receipt")),
                ("amount", models.DecimalField(blank=True, decimal_places=2, help_text="Total amount (for tracking material costs and taxes)", max_digits=12, null=True)),
                ("vendor", models.CharField(blank=True, help_text="Store or vendor name", max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("category", models.CharField(choices=[("materials", "Materials"), ("fuel", "Fuel"), ("equipment", "Equipment / Rentals"), ("supplies", "Supplies"), ("labor", "Labor / Subcontractor"), ("other", "Other")], default="other", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="receipts", to="businesses.business")),
                ("job", models.ForeignKey(blank=True, help_text="Link to a specific job (e.g. materials for this job)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="receipts", to="jobs.job")),
                ("uploaded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-receipt_date", "-created_at"],
            },
        ),
    ]
