# Generated by Django 5.2.11 on 2026-03-03 13:24

import financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_revenuecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, help_text='Optional; you can add a material cost without a receipt.', null=True, upload_to=financials.models.receipt_upload_to),
        ),
    ]
