# Generated by Django 6.0.2 on 2026-02-27 18:59

import django.db.models.deletion
import financials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_revenuecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this receipt was soft-deleted. Null means active.', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this revenue category was soft-deleted. Null means active.', null=True),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this revenue category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_revenue_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, help_text='Optional; you can add a material cost without a receipt.', null=True, upload_to=financials.models.receipt_upload_to),
        ),
    ]
