# Generated by Django 6.0.2 on 2026-03-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0036_business_default_fert_price_per_sqft'),
        ('financials', '0004_alter_receipt_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Scag V-Ride 52in, Stihl BR 800', max_length=200)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, help_text='Expected value at end of useful life', max_digits=10)),
                ('useful_life_hours', models.PositiveIntegerField(default=2500, help_text='Expected operating hours before replacement')),
                ('annual_maintenance', models.DecimalField(decimal_places=2, default=0, help_text='Estimated annual maintenance/repair cost', max_digits=10)),
                ('annual_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_cost_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Estimated fuel cost per operating hour', max_digits=6)),
                ('hours_per_year', models.PositiveIntegerField(default=1000, help_text='Estimated operating hours per year')),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assets', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaborBurdenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fica_rate', models.DecimalField(blank=True, decimal_places=2, help_text='FICA/Social Security (typically 7.65%)', max_digits=5, null=True)),
                ('futa_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Federal unemployment tax (typically 0.6%)', max_digits=5, null=True)),
                ('suta_rate', models.DecimalField(blank=True, decimal_places=2, help_text='State unemployment tax (varies 2-5%)', max_digits=5, null=True)),
                ('workers_comp_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Workers comp rate (landscaping avg ~4.4%)', max_digits=5, null=True)),
                ('health_insurance_per_employee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly health insurance cost per employee (flat $, not %)', max_digits=10, null=True)),
                ('pto_rate', models.DecimalField(blank=True, decimal_places=2, help_text='PTO accrual as % of wages (typically 3-8%)', max_digits=5, null=True)),
                ('other_burden_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Any other burden (uniforms, training, etc.)', max_digits=5, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labor_burden', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='OverheadExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. F-250 truck payment, GL insurance, shop rent', max_length=200)),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle Payment'), ('vehicle_insurance', 'Vehicle Insurance'), ('equipment_payment', 'Equipment Payment'), ('general_insurance', 'General Liability Insurance'), ('rent', 'Shop/Office Rent'), ('utilities', 'Utilities'), ('software', 'Software Subscriptions'), ('marketing', 'Marketing/Advertising'), ('admin_salary', 'Admin/Office Salary'), ('fuel', 'Fuel (general)'), ('phone', 'Phone/Internet'), ('license', 'Licenses & Permits'), ('accounting', 'Accounting/Bookkeeping'), ('other', 'Other')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount per period', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_expenses', to='businesses.business')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2022 Ford F-250, Crew cab truck', max_length=200)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_registration', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_mpg', models.DecimalField(decimal_places=1, default=15, help_text='Average miles per gallon', max_digits=5)),
                ('fuel_price_per_gallon', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
                ('estimated_annual_miles', models.PositiveIntegerField(default=20000)),
                ('annual_maintenance', models.DecimalField(decimal_places=2, default=0, help_text='Estimated annual maintenance (oil, tires, repairs)', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assets', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
