"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root if present (secrets stay out of version control)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in production (e.g. a 50-char random string).
_secret = os.environ.get("DJANGO_SECRET_KEY", "")
if not _secret and not os.environ.get("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes"):
    raise RuntimeError("DJANGO_SECRET_KEY must be set in production (DJANGO_DEBUG=0)")
SECRET_KEY = _secret or "django-insecure-dev-only-do-not-use-in-production"

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True so you see full error pages in development; set DJANGO_DEBUG=0 to disable.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

# In production, set ALLOWED_HOSTS (comma-separated) or leave unset.
# When PORT is set (e.g. App Platform, Render), allow .ondigitalocean.app so the app accepts requests.
_allowed = os.environ.get("ALLOWED_HOSTS", "").strip()
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
elif os.environ.get("VERCEL"):
    ALLOWED_HOSTS = [".vercel.app", ".now.sh"]
elif os.environ.get("PORT"):
    # App Platform, Render, etc. set PORT; allow default platform hostnames
    ALLOWED_HOSTS = [".ondigitalocean.app", ".render.com", "127.0.0.1", "localhost"]
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# For HTTPS in production, set CSRF_TRUSTED_ORIGINS (comma-separated), e.g. https://yourapp.com,https://www.yourapp.com
# On Vercel, set to your deployment URL(s), e.g. https://your-project.vercel.app
_csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()] if _csrf_origins else []

# Production security hardening (only when DEBUG is False)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "1").lower() in ("1", "true", "yes")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_otp',
    'django_otp.plugins.otp_totp',

    'accounts',
    'businesses',
    'customers',
    'jobs',
    'billing',
    'pricing',
    'dashboard.apps.DashboardConfig',
    'time_tracking',
    'property_estimator',
    'financials',
    'subscription',
    'messaging',
    'fertilization',
    'pricebook',
    'equipment',
    'service_agreements',
    'checklists',
    'inspections',
]

# Stripe: platform subscription (business pays you) + Connect (businesses accept invoice payments)
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_SUBSCRIPTION_PRICE_ID = os.environ.get("STRIPE_SUBSCRIPTION_PRICE_ID", "")
STRIPE_CONNECT_APPLICATION_FEE_PERCENT = float(os.environ.get("STRIPE_CONNECT_APPLICATION_FEE_PERCENT", "0") or "0")

# Twilio SMS — optional; set these env vars to enable outbound SMS
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")

# QuickBooks Online integration removed - using built-in features instead

_middleware = ['django.middleware.security.SecurityMiddleware']
try:
    import whitenoise  # noqa: F401
    _middleware.append('whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass
_middleware += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'subscription.middleware.SubscriptionRequiredMiddleware',
    'businesses.middleware.TimezoneMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE = _middleware
# 2FA uses django_otp and django_otp.plugins.otp_totp (see INSTALLED_APPS above).

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notification_unread_count',
                'messaging.context_processors.messaging_unread_count',
                'businesses.context_processors.terminology',
                'businesses.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# PostgreSQL / Supabase: set PG_URL or POSTGRES_URL (Supabase connection URI).
# On App Platform use Run Time scope and set the var on the web service component.
def _get_db_url():
    for name in ("PG_URL", "POSTGRES_URL", "DATABASE_URL", "SUPABASE_URL", "SUPABASE_DATABASE_URL"):
        raw = os.environ.get(name, "") or ""
        raw = raw.strip().strip('"').strip("'").replace("\n", "").replace("\r", "").strip()
        if raw and (raw.startswith("postgres://") or raw.startswith("postgresql://")):
            return raw
    return ""

_db_url = _get_db_url()
_platform_runtime = bool(os.environ.get("PORT"))  # App Platform, Render, etc. set PORT

import sys

if _platform_runtime and not _db_url:
    print(
        "[DATABASE] FATAL: A PostgreSQL URL is required when PORT is set (platform runtime). "
        "Set PG_URL, POSTGRES_URL, or DATABASE_URL on the web service runtime environment.",
        file=sys.stderr,
    )
    raise RuntimeError(
        "PostgreSQL URL not set for platform runtime. Refusing SQLite fallback in production."
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if _db_url and (_db_url.startswith("postgres://") or _db_url.startswith("postgresql://")):
    _parse_error = None
    try:
        import dj_database_url
        _db_config = dj_database_url.parse(_db_url, conn_max_age=600)
        _db_host = (_db_config.get("HOST") or "").lower()
        _is_supabase = "supabase.com" in _db_host or "supabase.co" in _db_host
        if _is_supabase:
            # Ensure SSL is required for Supabase connections
            if "OPTIONS" not in _db_config:
                _db_config["OPTIONS"] = {}
            _db_config["OPTIONS"]["sslmode"] = "require"
        DATABASES = {"default": _db_config}
    except Exception as e:
        _parse_error = e
        try:
            from urllib.parse import urlparse
            _parsed = urlparse(_db_url)
            _db_user = _parsed.username
            _db_pass = _parsed.password
            _db_host = _parsed.hostname or "localhost"
            _db_port = _parsed.port or 5432
            _db_name = (_parsed.path or "/").lstrip("/") or "postgres"
            _is_supabase = _db_host and ("supabase.com" in _db_host or "supabase.co" in _db_host)
            DATABASES = {
                "default": {
                    "ENGINE": "django.db.backends.postgresql",
                    "NAME": _db_name,
                    "USER": _db_user,
                    "PASSWORD": _db_pass,
                    "HOST": _db_host,
                    "PORT": str(_db_port),
                    "CONN_MAX_AGE": 600,
                    "OPTIONS": {"sslmode": "require"} if _is_supabase else {},
                }
            }
            _parse_error = None
        except Exception as e2:
            _parse_error = _parse_error or e2
        if _parse_error and _platform_runtime:
            import sys
            print(
                f"[DATABASE ERROR] POSTGRES_URL is set but parsing failed: {_parse_error!r}. "
                "Fix the URL or check special characters in the password (URL-encode them).",
                file=sys.stderr,
            )
            raise _parse_error
        elif _parse_error:
            pass  # dev: keep SQLite on parse error

# Startup log: which database is in use (visible in App Platform runtime logs)
import sys
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    _host = DATABASES["default"].get("HOST", "?")
    print(f"[DATABASE] Using PostgreSQL at {_host}", file=sys.stderr)
else:
    print("[DATABASE] Using SQLite (db.sqlite3)", file=sys.stderr)
    if _platform_runtime:
        raise RuntimeError(
            "SQLite is disabled on platform runtime. Configure PG_URL/POSTGRES_URL/DATABASE_URL (Supabase recommended)."
        )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# When BLOB_READ_WRITE_TOKEN is set (e.g. Vercel Blob store "fieldops-blob"), use Vercel Blob for uploads
if os.environ.get("BLOB_READ_WRITE_TOKEN", "").strip():
    STORAGES = {
        "default": {"BACKEND": "config.storages.VercelBlobStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage", "OPTIONS": {"location": MEDIA_ROOT}},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

# Supabase Realtime (for in-app messaging)
SUPABASE_PROJECT_URL = os.environ.get("SUPABASE_PROJECT_URL", "").strip()
SUPABASE_ANON_KEY = os.environ.get("SUPABASE_ANON_KEY", "").strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/accounts/login/'
# After password login we hit this view; it redirects to 2FA verify only on new devices
LOGIN_REDIRECT_URL = '/accounts/post-login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Session: stay logged in until inactive for this long. Each request extends the expiry.
# Default 2 weeks; set SESSION_COOKIE_AGE_SECONDS in .env to override (e.g. 2592000 for 30 days).
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE_SECONDS", 60 * 60 * 24 * 14))  # 14 days
SESSION_SAVE_EVERY_REQUEST = True  # extend session on every request (inactivity = no requests for SESSION_COOKIE_AGE)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # keep logged in after closing browser
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Two-factor auth (optional): pip install django-otp qrcode, then add apps & OTPMiddleware
# OTP_LOGIN_URL = '/accounts/verify/'
# OTP_TOTP_ISSUER = 'Field Ops'

# Email - each business configures Gmail in Settings; fallback for non-email use
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Mapbox for satellite imagery in Property Estimator (get free token at mapbox.com)
MAPBOX_ACCESS_TOKEN = os.environ.get("MAPBOX_ACCESS_TOKEN", "")

# Google Maps for Daily Routes: map view and route optimization by address (enable Maps JavaScript API, Geocoding API, Directions API)
GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "")
# Usage limits to prevent overages (10,000 free requests per month, then charged)
GOOGLE_MAPS_MONTHLY_LIMIT = int(os.environ.get("GOOGLE_MAPS_MONTHLY_LIMIT", "10000"))
GOOGLE_MAPS_DAILY_LIMIT = int(os.environ.get("GOOGLE_MAPS_DAILY_LIMIT", "0"))  # 0 = no daily limit
DEFAULT_FROM_EMAIL = "Field Ops <noreply@fieldops.local>"

# Cache: used by django-ratelimit and general app caching.
# In production set REDIS_URL (or CACHE_URL) to use Redis.
_CACHE_REDIS_URL = (os.environ.get("CACHE_URL") or os.environ.get("REDIS_URL") or "").strip()
if _CACHE_REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _CACHE_REDIS_URL,
            "TIMEOUT": int(os.environ.get("CACHE_TIMEOUT_SECONDS", "300")),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "default",
        }
    }

# Scheduled tasks run via platform cron jobs (DigitalOcean Jobs):
#   5 14 * * *  python manage.py send_scheduled_monthly_invoices
#  20 14 * * *  python manage.py send_invoice_reminders
#  35 14 * * *  python manage.py send_estimate_followups
#   0 15 * * *  python manage.py send_google_review_requests

# Structured logging (JSON-friendly key/value output)
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "format": "%(asctime)s level=%(levelname)s logger=%(name)s module=%(module)s message=%(message)s"
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "subscription": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}

# Optional Sentry hooks: install sentry-sdk and set SENTRY_DSN to enable.
SENTRY_DSN = os.environ.get("SENTRY_DSN", "").strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.0") or "0.0"),
            send_default_pii=False,
            environment=os.environ.get("SENTRY_ENVIRONMENT", "production" if not DEBUG else "development"),
        )
    except Exception as sentry_error:
        print(f"[SENTRY] Disabled: {sentry_error}", file=sys.stderr)
