# Generated by Django 6.0.3 on 2026-03-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0028_business_business_subtype_business_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricebookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricebook_categories', to='businesses.business')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pricebook.pricebookcategory')),
            ],
            options={
                'verbose_name_plural': 'pricebook categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricebookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('flat_rate_price', models.DecimalField(blank=True, decimal_places=2, help_text='Flat rate to charge customer for this item/service.', max_digits=10, null=True)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost for parts/materials.', max_digits=10, null=True)),
                ('labor_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated labor time in minutes.', null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('warranty_info', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricebook_items', to='businesses.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='pricebook.pricebookcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
