# Generated by Django 6.0.3 on 2026-03-05 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_deleted', 'created_at'], name='messaging_m_convers_149829_idx'),
        ),
    ]
