# Generated by Django 6.0.3 on 2026-03-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0029_business_booking_enabled_business_booking_token'),
        ('messaging', '0002_alter_messageattachment_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=20)),
                ('from_phone', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
                ('purpose', models.CharField(choices=[('booking_confirm', 'Booking Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('invoice_reminder', 'Invoice Reminder'), ('review_request', 'Review Request'), ('notification', 'General Notification'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
