# Generated by Django 6.0.2 on 2026-02-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_client_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Received messages are unread until viewed on the client profile.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='communication_preference',
            field=models.CharField(blank=True, choices=[('', '— Not set —'), ('email', 'Email'), ('sms', 'Text (SMS)'), ('both', 'Email and Text')], default='', help_text='How this client prefers to be contacted.', max_length=10),
        ),
    ]
