# Generated by Django 6.0.2 on 2026-02-16 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_clientmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_due_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override due date for this client: days from issue date (e.g. 15 = Net 15). Leave blank to use business default.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
