# Generated by Django 6.0.2 on 2026-02-16 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_invoice_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='fertilization_services_per_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For fertilization programs: how many applications per year (e.g. 4). Enables smart scheduling with other fertilization clients.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
