# Generated by Django 6.0.2 on 2026-02-27 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_recurring_and_fertilization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this customer was soft-deleted. Null means active.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
