# Generated by Django 5.2.11 on 2026-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_recurring_and_fertilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='google_review_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_review_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_review_last_prompt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_review_status',
            field=models.CharField(choices=[('never_asked', 'Never asked'), ('asked', 'Asked'), ('reviewed', 'Reviewed'), ('opted_out', 'Opted out')], default='never_asked', help_text='Tracks Google review outreach so clients are not repeatedly prompted.', max_length=20),
        ),
    ]
