# Generated by Django 6.0.3 on 2026-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_portal_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lawn_square_feet',
            field=models.PositiveIntegerField(blank=True, help_text='Total lawn area in square feet. Used for fertilization calculations and auto-pricing.', null=True),
        ),
    ]
