# Generated by Django 6.0.2 on 2026-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_rename_lawn_square_feet_to_yard_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lawn_polygons',
            field=models.JSONField(blank=True, help_text='Saved polygon coordinates from satellite measurement tool.', null=True),
        ),
    ]
