# Generated by Django 6.0.2 on 2026-03-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_add_lawn_polygons_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auto_charge',
            field=models.BooleanField(default=False, help_text='Automatically charge saved card when invoice is sent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Card brand (visa, mastercard, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of saved card', max_length=4),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID on the connected account (for card-on-file payments)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentMethod ID for saved card', max_length=100),
        ),
    ]
