# Generated by Django 6.0.2 on 2026-03-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_add_stripe_card_on_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billing_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('one_time', 'One-Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='prepaid',
            field=models.BooleanField(default=False, help_text='Client paid upfront — skip auto-invoicing for covered services.'),
        ),
        migrations.CreateModel(
            name='ContractLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='e.g. Mowing, Mulch, Spring Cleanup', max_length=200)),
                ('frequency', models.CharField(choices=[('per_visit', 'Per Visit'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('seasonal', 'Seasonal'), ('annual', 'Annual'), ('as_needed', 'As Needed')], default='per_visit', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('times_expected', models.PositiveSmallIntegerField(blank=True, help_text='How many times per year', null=True)),
                ('times_completed', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='customers.contract')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
