# Generated by Django 6.0.2 on 2026-02-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_require_completion_photo'),
        ('quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('push_invoice', 'Push invoice'), ('sync_payroll', 'Sync payroll'), ('oauth', 'OAuth')], max_length=32)),
                ('reference_id', models.CharField(blank=True, help_text='e.g. invoice id or payment id', max_length=64)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_error_logs', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
