name: Deploy FIELDLGX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: fieldlgx
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            /home/fieldlgx/deploy.sh
